version: "3.9"
services:
  syslog-ng:
    image: "balabit/syslog-ng:latest"
    ports:
      - 10514:514/udp
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - NET_BROADCAST
      - NET_RAW
      - DAC_READ_SEARCH
      - DAC_OVERRIDE
      - CHOWN
      - SYSLOG
    volumes:
      - ./data:/var/log/fireflies
      - ./conf/syslog-ng.conf:/etc/syslog-ng/syslog-ng.conf
      - ./conf/logrotate.conf:/etc/logrotate.conf
      - ./conf/cron/logrotate:/etc/cron.hourly/logrotate
    entrypoint: sh -c "service cron start && /usr/sbin/syslog-ng  -F"
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.1
    volumes:
      - ./data:/usr/share/filebeat/fireflies
      - ./conf/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: ["--strict.perms=false"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    stdin_open: true
    tty: true
    deploy:
      mode: global
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./conf/logstash/:/usr/share/logstash/pipeline/
      - ./conf/ruby/:/usr/lib/firefly/ruby/
      - ./conf/logstash_data/:/etc/stardust/pipeline/
      - ./conf/certificates:/etc/stardust/pipeline/certificates/
    stdin_open: true
    tty: true
    environment:
      - XPACK_MONITORING_ENABLED=false
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
